apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  labels:
    app: backend
    app.kubernetes.io/name: nuage-home
    app.kubernetes.io/component: backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-exec
  labels:
    app: backend
    app.kubernetes.io/name: nuage-home
    app.kubernetes.io/component: backend
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-exec
  labels:
    app: backend
    app.kubernetes.io/name: nuage-home
    app.kubernetes.io/component: backend
subjects:
  - kind: ServiceAccount
    name: backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend-exec
